phottype       : AUTO
mag_zeropoint  : 0.0
detect_thresh  : 10.0
snr_threshold  : 5.0
posmatch       : 1.0
clip_sigma     : 3.0
magmin_r       : 11.0
magmax_r       : 15.5
magmin_i       : 10.0
magmax_i       : 15.0
magmin_z       : 9.0
magmax_z       : 14.0
magmin_r_short : 9.0
magmax_r_short : 14.0
flagmax        : 3
zpmin_i        : 25.25
zpmax_i        : 25.75
zpmin_r        : 26.25
zpmax_r        : 26.75
zpmin_z        : 24.
zpmax_z        : 25.
zpmin_r_short  : 22.5
zpmax_r_short  : 23.5
